baseURL = 'https://ajfarkas.dev/'
languageCode = 'en-us'
title = 'Andrew J. Farkas'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[taxonomies]
  category = "categories"
